# Generated by Django 3.2.18 on 2023-05-12 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('company_city', models.CharField(max_length=255, verbose_name='公司城市')),
                ('company_address', models.CharField(max_length=255, verbose_name='公司地址')),
                ('company_contact', models.CharField(max_length=255, verbose_name='公司联系人')),
                ('company_manager', models.CharField(max_length=255, verbose_name='公司经理')),
                ('creater', models.CharField(max_length=255, verbose_name='创建人')),
                ('openid', models.CharField(max_length=255, verbose_name='Openid')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标签')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'db_table': 'company',
                'ordering': ['company_name'],
            },
        ),
    ]
